### ISSUE TITLE
Ejabberd component register user issue

### ISSUE THREAD

**Issue by lloydwatkin** [node-xmpp/node-xmpp-component#20] opened 2014-07-24 10:54 UTC
See https://github.com/node-xmpp/node-xmpp-component/issues/17 for background.

Including @sonnyp

Original post:

 I keep getting error code 400, type modify, bad request, but I don't see anything wrong with my iq message.

My ejabberd configuration:

    {5282, ejabberd_service, [ 
         { hosts, ["nodejs.myejabberddomain"], [{password, "admin"}] } 
    ]}

My nodejs Component code:

	var Component = require('node-xmpp-component')
		, ltx = require('node-xmpp-core').ltx;

	var component = new Component({
		jid       : "nodejs.myejabberddomain",
		password  : "admin",
		host      : "localhost",
		port      : "5282"
	})

	component.on('online', function() {
		console.log('Component is online')

		//Tried with both these iq's
		var iq = new ltx.Element('iq',{type:'set',id:'reg2', to: 'myejabberddomain'})
		.c('query',{xmlns:'jabber:iq:register'});
		
		//var iq = new ltx.Element('iq',{type:'set',id:'reg2', to: 'myejabberddomain', from: 'admin@nodejs.myejabberddomain'})
		//.c('query',{xmlns:'jabber:iq:register'});
		
		component.send(iq);

	})

	component.on('error', function(e) {
		console.error(e)
		process.exit(1)
	})
   
Anyone knows what I'm doing wrong? Any tips?

**Comment by sonnyp** [comment] 2015-01-23 10:22
@lloydwatkin thanks for raising this issue.

We've been building a node XMPP Component for Redbooth and we didn't experienced the issue.
We don't use ```iq``` though so might be related.

**Comment by sonnyp** [comment] 2015-02-14 23:24
Closing this, couldn't reproduce.

**Closed by sonnyp** 2015-02-14 23:24 UTC
Labels: bug

**Comment by eelcocramer** [comment] 2016-02-22 20:32
I've exactly this issue.

I have an xmpp component build with node-xmpp that has a connection with ejabberd. When I send an IQ message from a client it is routed correctly to the component but when the component answers to that IQ ejabberd generates an error message back to the component.

**Comment by lloydwatkin** [comment] 2016-02-22 20:39
It sounds like you have a different issue @eelcocramer. Could you please raise a new issue with your replication steps and a copy of the error message please?

**Comment by sonnyp** [comment] 2016-02-22 22:58
@eelcocramer also provide ejabberd version please

**Comment by sonnyp** [comment] 2016-02-24 09:49
fixed in 2.0.1
